os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
    # FOO
    - secure: "YoOKFb0hg/3kwA2H93tqmt/ezrOdhCk6WIBSTzA4hYC3o6pgmlvwSC5oaI+oTFKGh2pEDaxykBZ+hRfaUkNgnDIquaqTTtH0FjzO5VGRMSpXvMDABzGOgdBt3LvyG1GjxjnNEO1btfXsQFPp6yJiLctTv0c9XDnwJLi0abZgPWzUnS1Xn6iDLE/qH3mcF81til5FiMyp1o33nIb1VDdSJBlNi57yogaUrTCp0C1WghKVYIG9kqY2hPFJqNDOessngU0XYrog3dNYeN6o1c++mEnfWXnPGSdiuGEcBMuE1TzvUeDlC3J67+bVg6ohSfFZe10qeAKzkT7fslMUhMJ0DRpxMLvQk8Sy7LHqqfn7n6/JtAD2gBH5Kg8wPd4bMF8J1I6prx9m8PnhGD5qgiBC85hIQxpRoqNmiHkd3hWeo0I4X0SDBAwrRjutFi3ZjHPndCnlU15VhPILE/ARN1weyCeUce/G6jE7kCfDEhj9w9tm1pMm88yoc18zvOYzyTB2sz7jiKG8h2PCwRnMafSrVUrqO90EhuGiB16wxQzEFFirWynM2iXDBu00fje9JOfHTGiycD6UDRUGhzCMdLbDcgCO4aP5lr3pGQGi2cUBf+KNmzJbHx+WbU/4VSh2zB/3mwsDYnTV7/6xodOGyrcTVe0/3I3Vm9DZjAhJ/2Aqej4="
    # BAR
    - secure: "fQEcCN/R2aW4pAum71+cCcLrwe6R6QJxJb7GfpPY8D8VYRKLxQsAb9n0Gx3YMQ3nFKNAg+Pxbm+fHBnQCMSaueYhQTV5ku+p4E7Od8c2ofOYCaMOCGRi1dfITBppeB/YbdhIijq9+vMj7yL8nuJehroKtKOErl4M+KV9D+o2ncoc3Y5t32cQAx1xttyhcMlW6wpMk7QXfOo9uW9PN1kAHZcw+AyF2VhoMhScf3c8sEQoi+pE4d24SFdwQDh7uxLvPSlQOLoSRbeLt8goUpgIL5bGXyuquK9GlT0M90/MA/2HVJywiWGxQlvzx/dvkc85dLkg705L2LqrYyXj2X/cdZ0lJO/FIk5ZxSO/Evo+RhdswTakJPU9gZpLC44coAGnXP8jcMwXGWm1FuhrmaJW7gwssIhJMu6v37T69uWoqPNAmtgCb+wSFY4pliovYYxttNxP27m5cghORJ166VaVlcJoyY5EInfjcusBlMhG1r4FZy/xAi8CxCD/c3MaG62acUTuW1aep54mFS38seRGSFJNAD5aoJfJlLjiIGB/mrm9qKXAWVpsjYDSIa36K3sdYA6N48oi8UT0uJIEgz3tT0a0Ls8Cnwu27awrgp1S87wjKYuRr0QQoptz9+wvUNwAozobRQquOu4amysdLePwxljKgRs1dwOLl81ZTlRgdr8="
jobs:
  include:
    - stage: "sleep 109"
      script: echo $FOO 
